name: Laravel Report PHP 8.0
on:
  push:
    branches:
      - master
      - v*.*
  pull_request:
    branches:
      - master
      - v*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: actions/checkout@v2
        with:
            php-version: '8.0'
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Execute tests via PHPUnit
        run: vendor/bin/phpunit
